Fix Shmoose platform order
The site failed to build because platforms must be in alphabetical order:

```
python3 /var/tmp/src/xmpp.org/tools/lint-list.py clients.json
ERROR: entry 'Shmoose': platform order must be: 'Linux', 'Sailfish OS' (platforms must be ordered alphabetically)
Found 1 severe violations. Please fix them.
```